### ISSUE TITLE
TypeError: jsf.option is not a function

### ISSUE THREAD

**Issue by benchem** [xie-shujian/k3s#1]
按照您的脚本，部署出来的yapi执行会报一下错误，不清楚是yapi产品问题，还是底包环境问题。

`
error: TypeError: jsf.option is not a function at Object.exports.schemaToJson (/usr/src/app/server/utils/commons.js:52:7) at interfaceController.schema2json (/usr/src/app/server/controllers/interface.js:1178:28) at /usr/src/app/server/utils/commons.js:436:28 at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async module.exports (/usr/src/app/server/middleware/mockServer.js:152:15)
`

**Comment by xie-shujian** [comment]
使用nodejs11，不要使用高版本

**Comment by benchem** [comment]
thx
